### ISSUE TITLE
[Suggestion] An NBT editor

### ISSUE THREAD

**Issue by BookWyrm114** [JFronny/MeteorAdditions#10]
A fully-featured NBT editor, similar to [Infinity Item Editor](https://www.curseforge.com/minecraft/mc-mods/infinity-item-editor/files), but preferably also with the ability to open and edit the contents of storage blocks whilst they are in your inventory (this, of course, would only work in creative mode, just like the NBT editor, but would greatly aid in making nested shulkers). Also I know that Infinity Item Editor is for forge, I'm not asking for a port or anything like that, just that the editor should have many of it's features, as Infinity Item Editor is probably the most powerful NBT editor I know of. This would probably take a while to make but currently there aren't any really good NBT editors for fabric, and it would make an amazing addition to this addon.

**Comment by JFronny** [comment]
Meteor already provides basic NBT editing capabilities by default (I made those btw).
Anything more complicated than that is better suited for a standalone mod imo.
Also, I believe that the basic editing in meteor should be enough for most use cases and am not willing to design an overly convoluted UI around it for no purpose.

**Comment by tympanicblock61** [comment]
> 

i agree the nbt editor is really basic and needs a update

**Comment by tympanicblock61** [comment]
> > 
> 
> i agree the nbt editor is really basic and needs a update

or a way to save nbts and load them by making a new command like .nbtload kit1

**Comment by JFronny** [comment]
`.enchant`, `.give`, `.nbt copy` and `.nbt paste` should cover both easier interfaces for common tasks and a generic interface. I don't see any need for more.

**Comment by tympanicblock61** [comment]
ok

**Comment by tympanicblock61** [comment]
> `.enchant`, `.give`, `.nbt copy` and `.nbt paste` should cover both easier interfaces for common tasks and a generic interface. I don't see any need for more.

what is your discord i need to ask you a few questions about nbt

**Comment by JFronny** [comment]
I don't use, nor want to use, discord for contacting people any more than necessary.
You can, however, contact me through [other channels](https://jfronny.gitlab.io/contact.html)

**Comment by tympanicblock61** [comment]
ok well i was gonna ask how do you use a item string like command_block to spawn in a item in java

**Comment by tympanicblock61** [comment]
like the coding language not the game

**Comment by tympanicblock61** [comment]
> I don't use, nor want to use, discord for contacting people any more than necessary. You can, however, contact me through [other channels](https://jfronny.gitlab.io/contact.html)

ok well i was gonna ask how do you use a item string like command_block to spawn in a item in java the coding language

**Comment by JFronny** [comment]
1. This addon is open source and creating items for the creative tab is a suppoerted and documented feature
2. If you want something else, this issue is not the place for it
