### ISSUE TITLE
Request from a local dumbass:Its about the extra creative tab

### ISSUE THREAD

**Issue by ALT2652544** [JFronny/MeteorAdditions#14]
just gonna keep it simple i just want the extra creative tab with the op items with the command if you can make it into i mod please thatll help me soo much.

i cant code for shit thats why im asking.

**Comment by JFronny** [comment]
No

**Comment by ALT2652544** [comment]
;-;

**Comment by ALT2652544** [comment]
will you do it for 15 $ usd

**Comment by JFronny** [comment]
No. I will not maintain another mod for no reason.
Developing and not maintaining one wouldn't work either, since it'll likely cease to function soon, should I choose to do that
