### ISSUE TITLE
Creative Item Tab

### ISSUE THREAD

**Issue by Savvakos7** [JFronny/MeteorAdditions#15]
How can I see it?Do I have to press a specific button or command?

**Comment by JFronny** [comment]
It's a creative tab.
Get in creative mode, and it'll appear next to the other ones.

**Comment by Savvakos7** [comment]
> It's a creative tab. Get in creative mode, and it'll appear next to the other ones (assuming you have Fabric API).

It doesn't,and I have fabric api,the add-ons I have for meteor are AllahHack,MeteorCrashAddon, MeteorRejects and your addon.

**Comment by Savvakos7** [comment]
> It's a creative tab. Get in creative mode, and it'll appear next to the other ones (assuming you have Fabric API).

Bruh why you close the issue,it doesn't even show when I'm in creative.However the puking item module shows up on misc.
