### ISSUE TITLE
Crash with google chat

### ISSUE THREAD

**Issue by maplepy** [JFronny/MeteorAdditions#17]
https://mclo.gs/QdZmJtI

**Comment by JFronny** [comment]
MeteorAdditions is not yet updated for 1.19.1 apparently (I thought I had done that) and the included googlechat version is outdated. You can try manually installing google-chat 0.4.0 from modrinth or curseforge

**Comment by maplepy** [comment]
Ooh alright my bad, I thought I downloaded the 1.19.1 aha :) 

Alright will do thanks :)
