### ISSUE TITLE
Could you update to 1.19.1?

### ISSUE THREAD

**Issue by LetMeKillMyself** [JFronny/MeteorAdditions#18]
Hello JFronny is it possible to update MeteorAdditions to 1.19.1 I think this is one of the best addons for meteor and I have used it a lot but now I cannot.
I hope you see this fast :D

thanks for reading

Greetings Pax. from Youtube

**Comment by LetMeKillMyself** [comment]
Also 1.19 Does not seem to work for me.

**Comment by JFronny** [comment]
I'm currently on holiday, so you'll have to wait a week or two. I do plan on updating this once I'm back home, though.

**Comment by LetMeKillMyself** [comment]
That would be great Thanks have a great rest of you holiday :D
