### ISSUE TITLE
[bug] carpet mod

### ISSUE THREAD

**Issue by krispyking24** [JFronny/MeteorAdditions#23]
when u have both meteor additions and carpet mod on the client all carpet mod commands feedback all show bank chat I tested in 1.19.3 with carpet version v1.4.96+v230201 with meteor dev build v0.5.2-1781 with the meteor additions version released on dec 15 of 2022 at the time of typing this all of those versions are the latest most up to date versions
![image](https://user-images.githubusercontent.com/77263183/218983462-e313a5c0-78c2-4580-9f9e-007a2ceedf94.png)

**Comment by JFronny** [comment]
Seems to actually be an issue between translater and carpet.
I'll try to fix this, but you can try toggling the Translater module on and off again in the meantime.

**Comment by krispyking24** [comment]
i don't remember having the translator module turned on but ok thanks

**Comment by krispyking24** [comment]
oh it wasn't clear what i ment by "ok thanks" this was me trying to say ok i'll give it a go
