### ISSUE TITLE
Suggestion: item-group-remove

### ISSUE THREAD

**Issue by Ompyl** [JFronny/MeteorAdditions#27]
There is only the item-group-add command, so if you add an item accidently, you can't remove it.
A simple item-group-remove command would help

**Comment by JFronny** [comment]
That command only exists to make saving items with complex NBT easier.
In truth, it is simply a convenient interface over `.minecraft/meteor-client/additions_items.txt`, where the items are stored and can be edited and deleted at will.
As such, adding a command to remove items makes little sense and is not planned.

**Comment by Ompyl** [comment]
"In truth, it is simply a convenient interface over .minecraft/meteor-client/additions_items.txt" ins't too convenient without an nbt editor but ok

**Comment by JFronny** [comment]
It is a text file.
You don't need (and can't use) an NBT editor to edit it.
