### ISSUE TITLE
Cant start the Game with this Addon / Mod "requires any version of fabric-api, which is missing!"

### ISSUE THREAD

**Issue by Eragon1250** [JFronny/MeteorAdditions#29]
I tryed starting it with different versions of fabric and only together with Meteorclient, nothing worked, the game wont start, fabric and its API are installed

Error Copyed:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, any version.
Unmet dependency listing:
	 - Mod 'MeteorAdditions' (meteor-additions) 1.2.0 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Eragon1250** [comment]
When i try starting it without Meteor client i get the missing Meteor client in the Error message which means it checks the versions and wont start and its maybe not an hard error like dividing by "0". So maybe the Error is in the "Fabric identification Algorithm".

Maybe it could be fixed with just initializing the start anyway even if it thinks the Version is wrong, or just skipping the check.

**Comment by JFronny** [comment]
Current versions of Fabric API use the `fabric-api` mod id, while `fabric` was used previously. Make sure you have installed an up-to-date version of Fabric API, which is required for this addon. If you have one already, please provide a full log including fabric-loaders mod tree.

**Comment by Eragon1250** [comment]
You mean this with fabric API?

https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4757925

**Comment by JFronny** [comment]
For logs, see [this](https://fabricmc.net/wiki/player:tutorials:logs_ml:windows) wiki page.
A quick local test confirms that this is not an issue with MeteorAdditions, since a simple test instance with `fabric-loader-0.14.22-1.20.1`, Fabric API with `0bc5ff2d5df97e2c654789bd5e325d89f9ff883e`, Meteor Client with `de66315531988cbdddbed2bc66533cd9589eb91b` and MeteorAdditions with `309a4f32c689808b2df2efc83c1460b612c10cca` works just fine.
Make sure you are really loading a current fabric api and that your checksums match, as something going wrong with your download is one possible source for issues.

**Comment by Eragon1250** [comment]
[latest.log](https://github.com/JFronny/MeteorAdditions/files/12777092/latest.log)

**Comment by JFronny** [comment]
It does not. Try replacing meteoradditions with some other mod that requires, but does not bundle (!) fapi and see if that works. As I said, it works on my machine™, so this is something you will probably have to solve on your own and not an issue with this project.

**Comment by Eragon1250** [comment]
Other Mods are working,  what do you mean with bundle fabricAPI?

**Comment by JFronny** [comment]
A mod like appleskin.
Some mods only depend on a subset of fapi and can JiJ that subset, preventing users from having to download the full FAPI at the cost of a good bit of storage for every single mod doing so.
I do not bundle FAPI.
