### ISSUE TITLE
How to compile it?

### ISSUE THREAD

**Issue by unixquuw** [JFronny/MeteorAdditions#3]
As i said in title, how do i compile this on arch linux?

**Comment by JFronny** [comment]
You can:
- Use the build from [actions](https://github.com/JFronny/MeteorAdditions/actions/workflows/gradle.yml)
- Use a system-wide gradle install (`pacman -S gradle; gradle build`)
- Use gradlew (`./gradlew build`), though you may need to install dependencies for this
