### ISSUE TITLE
Warn users about their ip being leaked when using the server scanner feature.

### ISSUE THREAD

**Issue by etianl** [JFronny/MeteorAdditions#30]
I was just perusing your code today and noticed the scanner feature uses masscan which uses a custom TCP stack which will bypass any VPN client used by the user. Maybe either use a different port scanner, or warn users that this will leak their IP to the servers that are pinged.

**Comment by JFronny** [comment]
That script is a separate **example** and not shipped with or executed by the client. It exists to allow users to understand how they would automatically obtain importable server lists.

**Comment by etianl** [comment]
Oh good, I was spooked there for the people using it
