### ISSUE TITLE
Causes crashing

### ISSUE THREAD

**Issue by DrekAnon** [JFronny/MeteorAdditions#31]
Not sure why, but sometimes when you press your inventory key, it'll crash your game with exit code -1 (0xffffffffffffffff). Translator also tends to break chat I think by trying to translate too many messages (such as server operator messages)

**Comment by JFronny** [comment]
Exit codes don't mean anything in the context of MC. A crash report would probably be more helpful.
Translater supports a whitelist (and blacklist) for messages via regex, so you can set up filters that detect messafes that don't need translation for your particular server. This can not be automated, so you'll need to do it yourself.

**Comment by JFronny** [comment]
I'm closing this issue to clean up, since you didn't respond, and I am thus unable to do anything to help. Please reopen it with additional details if you still have these problems.
