### ISSUE TITLE
another feature

### ISSUE THREAD

**Issue by Vitalasy** [JFronny/MeteorAdditions#8]
translator and auto place from wurst.

**Comment by JFronny** [comment]
- Translating already exists as [google-chat](https://gitlab.com/jfmods/googlechat)
- What does AutoPlace do?

**Comment by Vitalasy** [comment]
> * Translating already exists as [google-chat](https://gitlab.com/jfmods/googlechat)
> * What does AutoPlace do?

ii don't the exact name of that module but it places specified block beneath you in a specified area like 3x3 2x2 etc.

**Comment by JFronny** [comment]
A way to configure google-chat like a meteor module has been added in https://github.com/JFronny/MeteorAdditions/commit/d3ed4eba7ee720ce061a9998d026adfcf73b92eb

By your description, auto place seems to be a scaffold variant. Some other module probably has that already

**Comment by Vitalasy** [comment]
> A way to configure google-chat like a meteor module has been added in [d3ed4eb](https://github.com/JFronny/MeteorAdditions/commit/d3ed4eba7ee720ce061a9998d026adfcf73b92eb)
> 
> By your description, auto place seems to be a scaffold variant. Some other module probably has that already

checked some possible modules but couldn't find that auto place alternative. would be really nice if you add it thank

**Comment by JFronny** [comment]
*addon

**Comment by JFronny** [comment]
Closing as this is a feature of [another addon](https://github.com/Declipsonator/Meteor-Tweaks) already
